apiVersion: v1
kind: Service
metadata:
  name: interaction-service-active
  namespace: dev
spec:
  selector:
    app: interaction-service
  ports:
    - name: http
      port: 3004
      targetPort: 3004

